const dictionary = require("./dictionary")

console.log(" ")
console.log("nouns length is " + dictionary.nouns.length)
console.log("properNouns length is " + dictionary.properNouns.length)
console.log("verbsIng length is " + dictionary.verbsIng.length)
console.log("verbsS length is " + dictionary.verbsS.length)
console.log("verbsEd length is " + dictionary.verbsEd.length)
console.log("adverbs length is " + dictionary.adverbs.length)
console.log("adjectives length is " + dictionary.adjectives.length)
console.log("places length is " + dictionary.places.length)
console.log("events length is " + dictionary.events.length)
console.log(" ")