// DICTIONARY: nouns are singular common nouns; properNouns are singular proper nouns; verbsIng are gerund phrases
// verbsEd are past tense verbs; adverbs are adverbs ending in -ly; places are prepositional phrases mostly giving location
let nouns = ["mystery", "love", "jock", "doober", "cadbury egg", "shoobie", "starburst jellybean", "oarfish", "oral hygeine", "dictionary", "goober", "scuba diving", "graham cracker", "gardening", "airplane", "pepperoni", "blue bird", "airhead", "dog", "rancho", "sushi dinner", "hockey", "football", "bare-knuckle boxing", "parade", "friend", "butt", "pudding on a ritz (like the cracker lmao)", "manatee", "maple", "sky", "blood", "tote", "egg", "potion", "chai latte", "chunk", "hot sauce", "medium double double", "boot", "plastic bag", "wealth equality", "captain falcon's nair", "single-use cutlery", "slapper", "magnet", "telephone", "girl scout cookie", "dime", "fake out", "fuckin' fake out", "chicken nugget", "bargain", "tadpole", "fuck up", "work of art", "napkin", "motif", "milkshake", "belly", "champagne", "whale", "shark", "whale shark", "healthy soil", "dirt", "soft pretzel", "queen", "rope", "hawk", "ear", "origami", "frog", "mood ring", "scooter", "nametag", "succulent", "Flamin' Hot Cheetos", "paystub", "PEANUTS", "funfetti cake", "lil soy bean", "pink eye", "grande vanilla latte", "joy con", "subway", "spongebob screenshot", "beautiful hair", "groovy lunch hour", "noosa", "berry", "mouthful of spiders", "old haunted guitar covered in blood that jesus found by the dumpster, ALLEGEDLY"]
let properNouns = ["me", "steve martin's banjo", "talking dog at the shell shack", "nbc peacock", "muppets christmas special", "Babe", "pelican man", "lunch lady who loves you :)", "franklin the turtle", "larry boy", "npr", "terry gross", "madonna", "Jeb!", "josh groban's angelic voice", "fart vader", "mr. buckley", "glenn close", "gillian anderson", "scully", "mulder", "guy fieri's bottle of bleach", "helen obama carter", "chef bobby flay", "king george", "meryl streep's vocal coach", "bob odenkirk", "BIBLICAL JONAH", "spanky", "fred armisen", "mail robot? like from the 80s?? that would deliver mail????", "lionel richie", "patton oswalt", "chubby jonah hill", "skinny jonah hill", "sarah crowley incarnate", "punk rock chicken", "this dooskbot", "timmy and tommy", "ghost of the great barrier reef", "squidward tentpoles", "swagner", "chip", "cramorant", "goldie", "kapp'n", "santiago", "julian casablancas", "sydnee mcelroy", "yellow yoshi (bisexual)", "gritty", "captain bones", "crazy bones", "my closest friend @goodtimebot", "my nemesis @rchllxbot", "guthix", "jason funderburker", "rachelle", "meg", "hillary", "matt", "justin true doe", "kyle maclachlan", "candy isle", "mighty sapling warrior", "shiny wooloo", "tom nook", "warlord acorn", "all the good folks at @FinjiCo", "barack obama", "magic johnson", "dominic the donkey", "italian christmas donkey", "Fargo, on FX returning April 20,", "meryl streep", "Splatoon 2 for the Nintendo Switch", "animal crossing", "chelsea", "calamity ganon", "kate winslet", "greta gerwig", "brie larson", "keri russell", "HBO", "dumb dead idiot john mccain", "momo", "celeste", "helen", "pashmina", "Andre 3000", "yoshi", "kk slider", "santa claus herself", "doctor kran", "ridley", "the alien from alien", "non canonical jar jar binks", "ronan farrow", "pedro martinez", "pawniard", "hawlucha", "dunsparce", "chili", "chai", "canuck", "uncle sam", "garnet", "the perf @girlfoyle", "daymor", "avy", "big sean", "bo horvat", "tina fey", "will", "izzy", "bart the chameleon", "jack eichel", "bernie", "elizabeth warren", "the original rascal", "human girl @andrea_oaks", "greninja", "donkey kong", "diddy kong", "kirby", "mr funk", "my ex", "whale prom", "pokemon", "human @asst_to_hutch", "human @dnmckn", "my roommate", "fart", "inkling", "Doctor Who", "class traitor", "CAPTAIN MAGMA", "isabelle", "andrea's favorite plant", "bulbasaur", "hutch", "zoey the dog", "andrea", "dooski", "king nightmare spiderlord", "hillary", "mudkip"]
let verbsIng = ["rigging a primary", "watching Dad trying not to cry during a World War II documentary", "watching a World War II documentary with dad", "killing them with kindness", "hacking JSTOR", "dating the librarian", "crossing the picket line", "stepping in shit at the dog park", "not brushing their teeth", "watching a fan-made youtube compilation of peridot yelling", "going back in time and killing andrew jackson", "going back in time and killing andrew jackson wearing a salmon suit", "being a normie", "giving up the gun", "getting eliminated in the appetizer round of chopped ):", "showing my best friend squidward to everyone in town", "losing the egg hunt", "winning the egg hunt", "cheating during the egg hunt", "'wow' reacting only", "cracking open a cold one with the boys", "letting everyone know that the boys are back in town", "snacking on a bowl of croutons", "camping in the backyard", "camping in the backyard while wearing a salmon suit", "bicycle kicking the christmas ham", "playin' in the sprinkler", "showing my best friend squidward to everyone in town wearing a salmon suit", "having a bowl of nails for breakfast without any milk", "screaming into a body pillow", "burning the pizza", "chugging a half gallon of heavy cream", "spilling milk everywhere", "looking fresh", "snatching a relic", "listening to the hit rochester band @candy_isle on spotify", "promoting sustainable forestry", "hosting an outdoor barbecue with the boys from the office", "constructing a guillotine", "savoring the delicious taste of airheads", "putting on the ritz", "asking out my crush", "stealing flowers", "getting hot during the quarantine despite what @asst_to_hutch said", "crying like a tall child", "feeling fuzzy from all the facebook comments from mom's friends", "sealing jeff bezos away for eternity", "doing a little dance on the catwalk", "throwing out my important tax files", "turning back", "squeezing the last bit of toothpaste out", "ordering pizza", "ordering systemic change in our social order", "spreading COVID-19 on purpose", "straight flexing", "exploring the entire world", "sprinting from a bad dream", "rolling down a hill", "falling right out of the sky", "dropping the load", "putting all my amiibo in the washing machine", "fucking up", "invading iraq", "literally just vibing", "fumbling for words", "spinning around and around", "scheming on the low", "jumping", "showering in pig's blood like that one scene in episode three season one of the FX series, Fargo, returns April 20 #sponsored", "birding", "grasping at straws", "punishing strangers for their transgressions", "calling tom hanks to ask an important question", "figuring out a way to ask me out :)", "dancing like everyone's watching", "cheating on their math test", "doing a moby dick speedrun", "becoming the real cool cat lately", "breaking up with me", "trying to prove a point", "really going to die on this hill, huh", "eating a burrito shaped like me (by design)"]
let verbsS = ["darkens", "pees", "backflips", "dunks", "panic hugs", "poops", "farts", "dabs", "sneezes", "yeets", "laughs", "vibes", "flexes", "wheels and deals", "shits", "stumbles", "tweets", "burns", "stabs", "celebrates", "smacks", "bangs", "slaps", "kisses", "dances", "yearns", "hugs", "embraces"]
let verbsEd = ["kissed", "defeated", "smashed", "discovered", "scrubbed", "smoked", "lost", "dabbed", "ratted", "drove", "divorced", "listened", "fell in love", "splatted", "vibed", "chuckled", "ate loudly", "flexed", "kissed", "traded", "battled", "transformed!", "performed", "screamed", "schucked", "drank", "wiggled", "snuggled", "came undone", "fused", "fuckin' GAMED"]
let adverbs = ["violently", "gorgeously", "extrmeely", "lovingly", "goonishly", "delightfully", "hastily", "loudly", "barely", "nautically", "bulbasaurly", "menacingly", "rudely", "polietly", "drunkenly", "randomly", "literally", "shittily", "gently", "goofily", "longingly", "desperately", "proudly", "excitedly", "shakily"]
let adjectives = ["mean", "salty", "weird", "space", "fictional", "lucky", "friendly", "sick", "super", "cool", "asinine", "good", "dope as hell", "nautical", "nude", "fresh to death", "fresh", "inky", "stinky", "wet", "spicy", "blue", "jazzy", "stanky", "brazed"]
let places = ["in Kirby's Dreamland", "with a box of scraps", "in the typhoon lagoon wave pool", "in line at payless shoesource", "at the pizza hut", "at the taco bell", "at the combination pizza hut-taco bell", "on jamaica avenue", "in the house tonight", "on robot pirate island", "on nightmare tarantula island", "in the middle of charging up a booyah bomb", "in the Vatican", "in quebec", "inside the milk fridge at wegmans", "in the lancelot parking lot of dulac", "in the dooskbot server, bayBEE", "in line at Federal Donuts", "under a dumpster", "on Amtrak", "on SEPTA", "on the LIRR", "at work", "at Mighty Taco", "at the Phoebe Bridger's concert", "by the docks", "near one of those classic active shootouts", "at the chili's", "in the applebee's bathroom", "on foreign land", "in the Long Island Sound", "in heaven", "in the Deep Sea Metro", "in the belly of a whale, like jonah", "in woody from toy story's boot", "on Red Couch", "during a Philadelphia sports riot", "inside a secret", "at the peach mag reading", "at the Clam Bake", "at the airport", "at baggage claim", "where we met", "where we joined body and soul together", "in Hawaii!", "in peach mag headquarters"]
let events = ["cause the COVID-19 pandemic", "the age of imperialism", "the worm", "the founding of sharkland", "the ice bucket challenge", "9/11", "the sinking of the lusitania", "Y2K", "the miracle on ice", "the chicago fire", "sports!", "the space landing", "the destruction of hyrule", "the JFK assassination", "pull off the best birthday surprise party ever!", "this", "all of vietnam", "start the titular fire in Billy Joel's classic We Didn't Start the Fire"]
let endings = [":)", "/:", "lol", " :')", "this says a lot about our society", " :/", " lmao", " ok", "ha haa", "carpe diem!", "waka waka!", "go bills", "o no", ":3", "c:", "and uh, coconut crab", ":/", "please call me", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]

module.exports = {
    nouns,
    properNouns,
    verbsIng,
    verbsS,
    verbsEd,
    adverbs,
    adjectives,
    places,
    events,
    endings
}